### ISSUE TITLE
CLI appears broken on latest

### ISSUE THREAD

**Issue by skylinematt** [assistant-ui/assistant-ui#1883]
In response to issue #1834 I've attempted to run the command but get the following:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/<user-dir>/.npm/_npx/ff25cc6233c5269c/node_modules/assistant-ui/dist/commands/create' imported from /Users/<user-dir>/.npm/_npx/ff25cc6233c5269c/node_modules/assistant-ui/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/<user-dir>/.npm/_npx/ff25cc6233c5269c/node_modules/assistant-ui/dist/commands/create'
```

I also noticed that the CLI seems to be broken in general (create, init etc has the same problem). Ive tried to create a new project and use a test project. Same result.

**Comment by sergiosegrera** [comment]
+1 I also experienced this

**Comment by free2dog** [comment]
I use `pnpx assistant-ui@0.0.48 init` succeeded for pnpm, maybe helps

**Comment by damithsenanayake** [comment]
+1 same. It's missing the 'create.js' in the index.js (we can only see 'create'). works fine on 0.0.48
