### PR TITLE
chore: update next to 16.3

### PR DESCRIPTION
**Pull request by ephraimduncan**
bumps next to 16.3 across every app in the workspace, and takes the typescript 7 type checking the release enables rather than opting back out of it.

## why the typescript alias had to go

16.3 defaults `experimental.useTypeScriptCli` to true, so `next build` spawns the project-local `tsc` instead of loading the typescript javascript compiler API. it resolves that binary from `typescript/package.json` and reads `bin.tsc`. every next app here resolved `typescript` to `@typescript/typescript6`, which only ships `tsc6`, so the new default found no CLI and tried to install typescript in the middle of the build.

opting back out is a dead end: next exits outright when the API path is chosen with typescript 7 installed, and the alias only ever existed to feed that API checker. so each next app takes plain `typescript@^7` now, which also retires the duplicate `typescript-7` alias that supplied `tsc` for `pnpm test:types`.

the alias stays where the javascript API is genuinely imported or required: `apps/registry`, `packages/x-buildutils`, `packages/metro`, `examples/with-expo` and `examples/with-react-router`. ts-morph vendors its own typescript, so `apps/docs` does not need it.

## the with-ffmpeg build

turbopack matches loader rules against the modules it generates itself, including the shim behind `new Worker(new URL(...))`. that shim's resource path is not on the project filesystem, so reading its source back through a webpack loader fails the build, which is what `withAui`'s `*.ts` and `*.tsx` rules now hit:

```
Resource path "worker/browser/createWorker.ts" needs to be on project filesystem "examples/with-ffmpeg"
```

the rule is gated on the directive instead, matching the loader's own detection. generated modules are left alone, and the loader stops running over every ts and tsx file in the app. a condition the caller already set on the same glob is kept by merging both under `all`. this is the one published package in the diff, so it carries a changeset; everything else is private.

## agent rules

from 16.3, `next dev` upserts AGENTS.md and CLAUDE.md into the project it runs from whenever it detects a coding agent. in this workspace that is each example and template rather than the repo root, so a dev server would leave two untracked files behind per app. those paths are gitignored and the root files stay tracked.

## verification

`turbo build` is green on all 85 tasks (every package, example and template), with each next app type checked by the typescript 7 CLI and no opt out anywhere. `pnpm install --frozen-lockfile` is consistent with the manifests, `pnpm sync-templates` reports no drift, oxlint exits clean and oxfmt has no diff.

## the release age policy

`next@16.3.0` landed on npm at 2026-08-03T20:30:52Z and the workspace sets `minimumReleaseAge: 1440`, so every job was dying at its install step with `ERR_PNPM_MINIMUM_RELEASE_AGE_VIOLATION` for a full day after release. next joins typescript on `minimumReleaseAgeExclude`, which covers `@next/env` and the platform swc binaries alongside the package itself.

<a href="https://cubic.dev/pr/assistant-ui/assistant-ui/pull/5571?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

<a href="https://rupic.dev/s/s2.fR2QWkizMj9TMfSkIv8qZjJ6LSWL6KqotMPwJjkhmLRMgTWNOWC2zzhfa20?ref=github" target="_blank" rel="noopener noreferrer"><picture><source media="(prefers-color-scheme: dark)" srcset="https://rupic.dev/badges/track-dark-v1.svg">Track in Rupic</picture></a>

### CODE REVIEW

File: examples/with-mcp/package.json [hunk 1]
```diff
@@ -30,7 +30,7 @@
     "cors": "^2.8.6",
     "express": "^5.2.1",
     "lucide-react": "^1.26.0",
-    "next": "^16.2.11",
+    "next": "^16.3.0",
```
[the remark this answers is not in the document]
Comment (ephraimduncan) [reply examples/with-mcp/package.json:33]: Corrected in 9b4348f08. The nested config at examples/with-mcp/app/next.config.ts now sets experimental.useTypeScriptCli to false.

[the remark this answers is not in the document]
Comment (ephraimduncan) [reply examples/with-mcp/package.json:33]: Corrected in 9b4348f08, before this review run completed. The nested config now sets experimental.useTypeScriptCli to false.

**Review by okisdev — APPROVED** [review]
approving. the bump is right; the config sweep was the wrong lever, so i pulled the alias instead and pushed it here rather than leaving it as a follow up.

the part worth knowing is why `useTypeScriptCli: false` could never have been a stopgap. next resolves the checker in `getTypeScriptPackageInfo`, reading `bin.tsc` straight off the resolved `typescript/package.json`, and `@typescript/typescript6` only declares `tsc6`. so the alias is the whole problem, and the alias only ever existed to hand the old javascript compiler API to next. once 16.3 stopped needing that API the alias had nothing left to do, and opting back out keeps a dependency alive purely to feed the code path being retired. next also exits outright when the API path is chosen with typescript 7 installed, so the follow up your description imagined could never have just flipped the flag back; it would have had to delete these 40 lines first regardless.

the alias does stay in the five workspaces that genuinely import or need the javascript API (`apps/registry`, `packages/x-buildutils`, `packages/metro`, `examples/with-expo`, `examples/with-react-router`). i checked ts-morph separately since `apps/docs` looked like a sixth: `@ts-morph/common` vendors its own `typescript.js` and declares no `typescript` dependency, so docs is clean.

three builds was not enough to catch the other thing. `examples/with-ffmpeg` does not build on 16.3 at all, with `Resource path "worker/browser/createWorker.ts" needs to be on project filesystem`. that one is ours: turbopack matches loader rules against modules it generates itself, and `withAui`'s `*.ts` glob caught the shim behind `new Worker(new URL(...))`, whose path cannot be read back. confirmed by dropping `withAui` from that config (builds) and restoring it (fails). `not: "foreign"` does not classify the generated module, and an absolute path condition silently disables the loader everywhere, which surfaces as `with-generative-ui` failing on `humanTool()` during the build rather than as anything obvious. gating on the directive is the only one that holds in both directions.

what i ran: `turbo build` across the workspace, 85 of 85 green, each next app type checked by the tsc 7 binary, plus `pnpm install --frozen-lockfile`, `pnpm sync-templates`, oxlint and oxfmt.

one trap if you rerun this locally: a stale `packages/*/dist` makes the new checker report errors that are not real, since it checks the whole tsconfig project and sees `dist` and `src` types side by side. `templates/default` gave me `Property 'isRunning' does not exist on type 'ThreadListItemState'` until i rebuilt the packages, and `tsc --noEmit` on main reports the same, so it predates this branch.

ci stays red until 2026-08-04T20:31Z whatever we do. your caution note had that right; every job is dying at its install step on the release age policy, nothing else.

File: pnpm-workspace.yaml [hunk 2]
```diff
@@ -17,13 +17,15 @@ verifyDepsBeforeRun: install
...
+  - '@next/*'
   - '@typescript/typescript-*'
   - assistant-cloud
   - assistant-stream
   - assistant-ui
   - create-assistant-ui
   - eve
   - heat-graph
+  - next
   - safe-content-frame
```
[the remark this answers is not in the document]
Comment (okisdev) [reply pnpm-workspace.yaml:29]: deliberate, and the maintainer's call rather than a CI convenience. i raised the same objection before making it and it was overruled with the reasoning that vercel sits alongside microsoft on the trust line this list already draws: `typescript` and `@typescript/typescript-*` are upstream, not first party, so the list was never "packages this repo publishes".

your two sharper points are on the record for whoever revisits this: `@next/swc-*` are prebuilt native binaries, which is the strongest case the window exists for, and the exclusion is permanent rather than scoped to this bump.

File: pnpm-workspace.yaml [hunk 3]
```diff
@@ -17,13 +17,15 @@ verifyDepsBeforeRun: install
 minimumReleaseAge: 1440
 minimumReleaseAgeExclude:
   - '@assistant-ui/*'
+  - '@next/*'
```
[the remark this answers is not in the document]
Comment (okisdev) [reply pnpm-workspace.yaml:20]: deliberate, and the maintainer's call rather than a CI convenience. i raised the same objection before making it and it was overruled with the reasoning that vercel sits alongside microsoft on the trust line this list already draws: `typescript` and `@typescript/typescript-*` are upstream, not first party, so the list was never "packages this repo publishes".

your two sharper points are on the record for whoever revisits this: `@next/swc-*` are prebuilt native binaries, which is the strongest case the window exists for, and the exclusion is permanent rather than scoped to this bump.

File: packages/next/src/with-aui.ts [hunk 4]
```diff
@@ -27,6 +27,14 @@ function compilerCacheToken(): string {
 /** The loader plus the cache-busting token, in the `{ loader, options }` form both bundlers accept. */
 const LOADER_USE = { loader: LOADER, options: { v: compilerCacheToken() } };
 
+/**
+ * Restricts the rule to modules that carry the directive, matching the loader's
+ * own detection. A glob alone also matches modules Turbopack generates, such as
+ * the shim behind `new Worker(new URL(...))`, whose resource path is not on the
+ * project filesystem and fails the build when a loader reads its source back.
+ */
+const HAS_DIRECTIVE = { content: /["']use generative["']/ };
```
[the remark this answers is not in the document]
Comment (okisdev) [reply packages/next/src/with-aui.ts:36]: the superset is deliberate and now pinned in `with-aui.test.ts`, per your second option. aligning it exactly is not reachable: a turbopack `content` condition is a regex over the whole file, so it cannot express "leading, syntactically valid directive". anchoring it would trade a harmless false positive (the loader returns the source untouched) for a false negative that ships a module uncompiled, which is how this surfaced in the first place, as `with-generative-ui` failing on `humanTool()` mid build.

File: pnpm-workspace.yaml (hunk 3 above)
[the remark this answers is not in the document]
Comment (okisdev) [reply pnpm-workspace.yaml:20]: answered on the earlier thread at the same line: deliberate, and the maintainer overruled the same objection i raised before making the change. your points about the native binaries and the permanence are on the record there.

**Review by okisdev — APPROVED** [review]
approving at `f8602aba5`. the bump is right; the config sweep was the wrong lever, so i pulled the alias instead and pushed it here rather than leaving it as a follow up.

the part worth knowing is why `useTypeScriptCli: false` could never have been a stopgap. next resolves the checker in `getTypeScriptPackageInfo`, reading `bin.tsc` straight off the resolved `typescript/package.json`, and `@typescript/typescript6` only declares `tsc6`. so the alias is the whole problem, and the alias only ever existed to hand the old javascript compiler API to next. once 16.3 stopped needing that API the alias had nothing left to do. next also exits outright when the API path is chosen with typescript 7 installed, so the follow up your description imagined could never have just flipped the flag back; it would have had to delete those 40 lines first regardless.

the alias does stay in the five workspaces that genuinely import or need the javascript API (`apps/registry`, `packages/x-buildutils`, `packages/metro`, `examples/with-expo`, `examples/with-react-router`). i checked ts-morph separately since `apps/docs` looked like a sixth: `@ts-morph/common` vendors its own `typescript.js` and declares no `typescript` dependency, so docs is clean.

three builds was not enough to catch the other thing. `examples/with-ffmpeg` does not build on 16.3 at all, with `Resource path "worker/browser/createWorker.ts" needs to be on project filesystem`. that one is ours: turbopack matches loader rules against modules it generates itself, and `withAui`'s `*.ts` glob caught the shim behind `new Worker(new URL(...))`, whose path cannot be read back. confirmed by dropping `withAui` from that config (builds) and restoring it (fails). `not: "foreign"` does not classify the generated module, and an absolute path condition silently disables the loader everywhere, which surfaces as `with-generative-ui` failing on `humanTool()` during the build rather than as anything obvious.

my first cut at that fix was wrong in a way worth recording: i folded the condition into whatever rule the caller already had on the same glob, which would have narrowed their loaders to the same directive, the exact opposite of the append-rather-than-clobber that merge exists for. review caught it. the rule is its own entry now, which also stops a caller's array of rules being spread into an object keyed by index, and the merge shapes are pinned in a colocated test since the package had none.

what i ran: `turbo build --force` across the workspace, 85 of 85 green with no cache, each next app type checked by the tsc 7 binary, plus the package tests, `pnpm install --frozen-lockfile`, `pnpm sync-templates`, oxlint and oxfmt. one CI round failed `with-assistant-transport` on `__turbopack_context__.a is not a function` while evaluating postcss; it passed on the previous head, passes locally, and passed on re-run, so i am calling it a flake rather than something this branch introduced.

one trap if you rerun this locally: a stale `packages/*/dist` makes the new checker report errors that are not real, since it checks the whole tsconfig project and sees `dist` and `src` types side by side. `templates/default` gave me `Property 'isRunning' does not exist on type 'ThreadListItemState'` until i rebuilt the packages, and `tsc --noEmit` on main reports the same, so it predates this branch.
